### ISSUE TITLE
error code s1001 (Network)

### ISSUE THREAD

**Issue by dannydvd21** [vmirage/TMDBTrailer.bundle#5]
IDK if it is my own fault but i am not able to play trailers.
After full library refresh my trailer give (error code s1001 (Network)).
any idea what could be the cause

EDIT: using plex version Version 1.19.5.3112 on Windows server
![error code s1001 (Network)](https://user-images.githubusercontent.com/63468487/89123827-a4b88c00-d4d2-11ea-8496-dffaacf4d0a1.jpeg)

**Comment by vmirage** [comment]
Need to see the logs to know what's going on. I'm guessing it's more likely Youtube plugin is unable to play the video.

**Comment by dannydvd21** [comment]
![log plex](https://user-images.githubusercontent.com/63468487/89321943-d9b81080-d683-11ea-9011-7c6896661d18.PNG)

**Comment by vmirage** [comment]
That's not the right log. 

Check your log folder as per the FAQ.
https://support.plex.tv/articles/200250417-plex-media-server-log-files/#:~:text=In%20general%2C%20log%20files%20will,the%20content%20for%20some%20platforms.

Then find `Plex Media Server/Logs/PMS Plugin Log/com.plexapp.agents.tmdbtrailer.log`

**Comment by dannydvd21** [comment]
[com.plexapp.agents.tmdbtrailer.log](https://github.com/vmirage/TMDBTrailer.bundle/files/5028435/com.plexapp.agents.tmdbtrailer.log)

**Comment by vmirage** [comment]
Error log seems to point to Youtube bundle having issues

Did you install the Youtube plugin as recommended in the installation instructions? 
https://github.com/kolsys/YouTubeTV.bundle

The error seems to be using the original Youtube bundle that came with plex. That bundle have issues with some youtube videos.

**Comment by dannydvd21** [comment]
i installed it but do i need to edit something?

**Comment by dannydvd21** [comment]
![youtubeTV](https://user-images.githubusercontent.com/63468487/89719328-769de500-d9c7-11ea-84d8-8e1fa25c06f2.PNG)

**Comment by vmirage** [comment]
Nothing to edit. Did you refresh your metadata after installing the YouTubeTV bundle or before? You might need to refresh it after installing the YoutubeTV bundle.

**Comment by dannydvd21** [comment]
Before and after,
Mayby it has to do with the firewall that is. Blocking something?

**Comment by vmirage** [comment]
I went through the YouTubeTV bundle code and it seems to fail. I've updated the code in YouTubeTV and requested for a pull request. In the mean time you can try install from https://github.com/vmirage/YouTubeTV.bundle while it's not merged into the main repository yet. Let me know if it works

**Comment by dannydvd21** [comment]
Will try it now

**Comment by dannydvd21** [comment]
Do I need to delete the bundle meta data first
Or Wil it over write

**Comment by vmirage** [comment]
You don't need to do anything. It should work. If not try restart Plex Server

**Comment by dannydvd21** [comment]
still not working I did notice that the plugin works on the server it is running on not when I view on my pc.
So looks to me als a firewall problem

**Comment by dannydvd21** [comment]
Nevermind it works on my main account but when I login to a sub account it gives the same network error.
![sub account](https://user-images.githubusercontent.com/63468487/89728158-5dc71b00-da2b-11ea-8667-3b341cee8ab6.png)

Same attempts are with the app.plex.tv link not my local 192.168.1.***

**Comment by vmirage** [comment]
I tested on my sub accounts and it works as well after installing the updated YouTubeTV bundle. So not exactly sure what problem you are encountering. Might need to check on the log again to see the details.

**Comment by dannydvd21** [comment]
doesnt update the logs when I view from sub account or from shared library user

**Comment by vmirage** [comment]
Odd. Mine does

**Comment by dannydvd21** [comment]
I will close the issue because I have bought the plex pass and it supports trailer for shared users, this is less tress for me

**Comment by ReenigneArcher** [comment]
I have created a working YouTube URL service that allows playback of YouTube extras.  https://github.com/LizardByte/PlexyGlass
